name: Build Api
on:
  push:
    branches:
      - 'main'
jobs:
  deploy:
    runs-on: ubuntu-22.04
    container: 
      image: node:16-bullseye

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install dependencies
      run: npm ci
      working-directory: api

    - name: Build
      run: npm run build
      working-directory: api
