name: Build Vue
on:
  push:
    branches:
      - 'main'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install node
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      run: npm ci
      working-directory: app

    - name: Build
      run: npm run build
      working-directory: app
      env:
        VITE_ENV: production

    # - name: Push
    #   uses: s0/git-publish-subdir-action@develop
    #   env:
    #     REPO: self
    #     BRANCH: gh-pages
    #     FOLDER: app/dist
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
    #     MESSAGE: "Build: ({sha}) {msg}" 

    - name: Deploy docs
      uses: JamesIves/github-pages-deploy-action@4.1.8
      with:
        branch: gh-pages
        folder: app/dist
