name: Build Vue
on:
  push:
    branches:
      - 'main'
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - name: install dependencies
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - run: cd app
    - run: npm ci
    - run: npm build

    - name: Push
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-pages 
        FOLDER: ./ 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        MESSAGE: "Build: ({sha}) {msg}"