name: Build Vue
on:
  push:
    branches:
      - 'main'
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - run: |
          ls 
          cd ./app
    - uses: actions/checkout@v2
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.1
      with:
        username: 'Stallos11'
        reponame: 'YamYam'
        cname: 'app.vleveque.com'
        token: ${{ secrets.GITHUB_TOKEN }}